### ISSUE TITLE
Accept single row stream as a data source?

### ISSUE THREAD

**Issue by roll** [frictionlessdata/tableschema-js#95] opened 2017-09-21 12:33 UTC
# Overview

For now we only support stream constructor as a `Table` data source because we don't do stream rewinding. It's possible to rewind stream - https://stackoverflow.com/questions/19553837/node-js-piping-the-same-readable-stream-into-multiple-writable-targets. It has to be investigated will it work for us because we should have an ability to do unlimited rewind operations on input stream. 

Initial discussion - https://github.com/frictionlessdata/tableschema-js/issues/92#issuecomment-330902373

# Plan

- [ ] investigate rewind solution and propose a design to this thread
- [ ] update `Table` class to support single stream as data source
- [ ] update readme for `Table` and `infer`
- [ ] write tests

**Comment by anuveyatsu** [comment] 2017-10-03 14:11
@roll I'm not sure if we need to rewind solution here. The goal is to be able to pass row stream directly. E.g., right now `source` can be stream factory which then initialized and piped to parser so we get row stream:

```javascript
// Stream factory
if (isFunction(source)) {
  stream = source()
  stream = stream.pipe(parser)
}
```

and what we want is to pass `stream.pipe(parser)`:

```javascript
// Row stream
else if (source.readable) {
  stream = source
}
```

**Comment by roll** [comment] 2017-10-03 14:18
@anuveyatsu 
In this case how it will be handling multiple reads like:
```
const source = new NodeStream()
const table = await Table.load(source)
table.read() // stream is ended
table.read() // ?
```
I'm not so familiar with Node Streams but my guest second read will not be possible.

**Comment by anuveyatsu** [comment] 2017-10-03 16:02
@roll yes, I see now. Seems like we need some variable to keep a duplicate of the stream. I don't see any other options...:

```javascript
async function createRowStream(source, parserOptions) {
  ...
  } else if (source.readable !== undefined) {
    // if stream is still readable then use original `source` stream
    if (source.readable) {
      duplicateStream = source.pipe(new PassThrough())
      stream = source.pipe(parser)
    } else { // if it is already fully read then use duplicateStream
      const forCurrentUse = duplicateStream.pipe(new PassThrough())
      const forLaterUse = duplicateStream.pipe(new PassThrough())
      duplicateStream = forLaterUse
      stream = a.pipe(parser)
    }
  }
  ...
  let duplicateStream
  ...
}
```

**Comment by roll** [comment] 2017-10-04 07:50
@anuveyatsu 
Rufus has suggested something like this. So I think it's cool.

Based on your example could we just multiplicate `table._source` before every `createRowStream` call inside `table.iter`? Something like this:

```javascript
  async iter({keyed, extended, cast=true, relations=false, stream=false}={}) {

    // Get row stream
    let source = this._source
    if (//source is stream) {
      const duplicateStream = this._source.pipe(new PassThrough())
      this._source = duplicateStream.pipe(new PassThrough())
      source = duplicateStream.pipe(new PassThrough())
    }
    const rowStream = await createRowStream(source, this._parserOptions)

// ...
```

**Comment by anuveyatsu** [comment] 2017-10-04 09:14
@roll sure - I will do PR today for this.

**Closed** 2017-10-04 16:33 UTC
Labels: feature, {contribute}
