### ISSUE TITLE
Hangs when streaming big CSV from remote location

### ISSUE THREAD

**Issue by felipesabino** [frictionlessdata/tableschema-js#109] opened 2017-11-18 11:46 UTC
## The issue

I am having an issue with the latest version (`1.4.1`) trying to read a big CSV 100k+ lines (like [this one](https://raw.githubusercontent.com/datasets/un-locode/master/data/code-list.csv) for example) from a downloading stream and to a stream output, but the resulting stream stops sending the `data` event after a while (in my tests it was around the 500th item, but this varies a lot) and it also does not send the `end` or `error` event ever.

## Reproducing

I drafted a [test case on my fork](https://github.com/frictionlessdata/tableschema-js/compare/master...felipesabino:bugfix/stream-download?expand=1) for this issue but not only it needs some work before going to the source but also I did not want that everybody started downloading a 100K+ lines CSV every time they ran the tests, so I am just pasting it here

```javascript
it('should iter with huge stream as a source', async function() {
  if (process.env.USER_ENV === 'browser') this.skip()
  this.timeout(100000)
  /* eslint max-len: off */
  const url = 'https://raw.githubusercontent.com/datasets/un-locode/6da8b0a849dd5a72ad53a98d294cf4fe2e2cfd4a/data/code-list.csv'
  const stream = (await axios.get(url, { responseType: 'stream' })).data
  const table = await Table.load(stream)
  const iter = await table.iter({ stream: true, keyed: true })
  return new Promise((resolve, reject) => {
    let total = 0
    iter.on('data', () => {
      total = total + 1
      console.log(total)
      // this stops being called after a while
    })
    iter.on('end', () => {
      // it is never called
      assert.equal(total, 107826)
      resolve()
    })
    iter.on('error', (err) => {
      // it is never called
      reject(err)
    })
  })
})
```

## What I have tried

I tried fixing the way the [stream is duplicated on the `iter` function](https://github.com/frictionlessdata/tableschema-js/blob/2cbd22043d85524e92371c19d9ee522a55a57515/src/table.js#L68-L70), replacing the following lines

```
if (source.readable) {
  const duplicateStream = this._source.pipe(new PassThrough())
  this._source = duplicateStream.pipe(new PassThrough())
  source = duplicateStream.pipe(new PassThrough())
}
```

by 

```
if (source.readable) {
  source = this._source.pipe(new PassThrough())
}
```

While it fixes the stream issue on my test case, it does not allow reading from the stream source twice, so other tests starts failing  like `should work with stream as a source`.

Anyway, I am willing to fix it but got kind of stuck now and would love some help going further.

Also, as I could not grasp exactly what is happening under the hood I must ask:

- Is it necessary to allow multiple `Table.read` executions when the source is a stream?
- What if the stream is not replayable? Is the data being duplicated n memory? 
- If so, isn't it a problem when handling huge data sources (which is the main use case for stream usage in the first place)?

**Comment by roll** [comment] 2017-11-18 12:35
@felipesabino
Thanks. Have you tried to pass function which returns a stream (one of the options for the source)

**Comment by roll** [comment] 2017-11-20 08:18
Oh I see it will not help because we copy a stream after calling the stream factory. I'm marking it as a bug. We'll think how to resolve it (cc @anuveyatsu)

**Comment by anuveyatsu** [comment] 2017-11-21 07:26
@roll @felipesabino one of my colleagues just experienced the same issue. I'll also think about this.

**Comment by felipesabino** [comment] 2017-11-22 11:31
@roll  Nice! And could you address some of my questions? I am thinking they might be useful to give some direction on how to fix this problem.

@anuveyatsu thanks!

**Comment by felipesabino** [comment] 2017-12-12 14:12
@roll 

I noticed that the `planning` tag has been added instad of `current` but I am not familiar on what does that mean.

Is there anything I or anyone could do to help fixing this problem?

**Comment by roll** [comment] 2017-12-12 14:23
@felipesabino 
We wasn't able to fix it in the current sprint (now it's a previous sprint). So we're looking forward to process it on the next sprint planning of the Frictionless Data team.

So for now if you'd like to make PR or contribute somehow - it's a great because next few weeks there will not be a work duplication.

**Comment by felipesabino** [comment] 2017-12-12 16:41
@roll 

> So for now if you'd like to make PR or contribute somehow - it's a great because next few weeks there will not be a work duplication.

I could, sure, but I just don't know ow to proceed. 

Could address the questions I added to the issue description? This would definitely guide on how to make the PR

```
- Is it necessary to allow multiple Table.read executions when the source is a stream?
- What if the stream is not replayable? Is the data being duplicated n memory?
- If so, isn't it a problem when handling huge data sources (which is the main use case for stream usage in the first place)?
```

**Comment by roll** [comment] 2017-12-13 11:53
@felipesabino 
I haven't answered earlier because was going to think about it) Not dived fully into this also now. Esp. because the support of stream has been initiated and added by @anuveyatsu. But I'll try to provide some thoughts:

> Is it necessary to allow multiple Table.read executions when the source is a stream?

That's a question for @anuveyatsu. By design there was no support for stream as a source. There was only support for functions returning a stream as a source. So stream management has been delegated to the client. I think we could live with no problem if some kind of source will be returning a `tableschema.Error` on replays if it's documented and replays are not needed. Also we could have a flag to make it explicit.

> - What if the stream is not replayable? Is the data being duplicated n memory?
> - If so, isn't it a problem when handling huge data sources (which is the main use case for stream usage in the first place)?

Again I'd like to give a mic here to @anuveyatsu =)

**Comment by felipesabino** [comment] 2017-12-14 17:10
Hi @anuveyatsu, whenever you have a chance could you address these questions above? It would really help me going forward with this PR without breaking too much backwards compatibility (if that is even a concern for this use case).

**Comment by felipesabino** [comment] 2017-12-19 12:20
@roll @anuveyatsu Hey guys, as I did not hear back I just submitted a PR #118 with some assumptions regarding how the library should behave regarding this issue.

> Is it necessary to allow multiple Table.read executions when the source is a stream?

I assumed _no_. As stream factories are supported, they it can be used instead to overcome this limitation.

**Closed** 2018-02-05 14:48 UTC
Labels: bug, {review}
